export const BoardNumbers = [
   { "id": "1" },
   { "id": "2", "color": "black" },
   { "id": "3" },
   { "id": "4", "color": "black" },
   { "id": "5" },
   { "id": "6", "color": "black" },
   { "id": "7" },
   { "id": "8", "color": "black" },
   { "id": "9"},
   { "id": "10", "color": "black" },
   { "id": "11", "color": "black" },
   { "id": "12" },
   { "id": "13", "color": "black" },
   { "id": "14" },
   { "id": "15", "color": "black" },
   { "id": "16" },
   { "id": "17", "color": "black" },
   { "id": "18" },
   { "id": "19" },
   { "id": "20", "color": "black" },
   { "id": "21" },
   { "id": "22", "color": "black" },
   { "id": "23" },
   { "id": "24", "color": "black" },
   { "id": "25" },
   { "id": "26", "color": "black" },
   { "id": "27" },
   { "id": "28", "color": "black" },
   { "id": "29", "color": "black" },
   { "id": "30" },
   { "id": "31", "color": "black" },
   { "id": "32" },
   { "id": "33", "color": "black" },
   { "id": "34" },
   { "id": "35", "color": "black" },
   { "id": "36" }
]